---
layout: default
title:  title here
date:   2015-10-08 15:46:20
categories: regional
group: regional
---


# map

```{r  overview}

the_whole   <- map.df # for mapping the grey areas

df <- subgrouping(region_to_report = region_to_report, gather=FALSE)

# merge data with the region info
overview.df <- merge(map.df,df[c("FAOST_CODE","subgroup")],by="FAOST_CODE")
overview.df <- arrange(overview.df, order)
#overview.df <- merge(overview.df,FAOcountryProfile,by="FAOST_CODE")

# define map unit
map_unit <- ""

# graticule
grat_robin <- spTransform(graticule, CRS("+proj=robin"))  # reproject graticule
gr_rob <- fortify(grat_robin)

if (region_to_report != "COF"){

source(paste0(root.dir,'./input/code/plot/plot_color.R'))

syb_part <- 1

## Part 1
colPart1 <- plot_colors(part = syb_part, 6)
col.main1 <- colPart1[["Main"]][1]

source(paste0(root.dir,"./input/code/plot/theme.R"))

# fill colors for the map
colPart = plot_colors(part = 1, 12)
mapColFun = colorRampPalette(c("white", colPart[["Main"]][1]))
nCol = length(unique(overview.df$subgroup))
tmpCol = mapColFun(nCol)[2]
mapColFun = colorRampPalette(c(tmpCol, colPart[["Main"]][2]))
mapColors = mapColFun(nCol)
}





# Create the plot
p <- ggplot(data=overview.df, aes(long,lat,group=group))
#  ---- grid below the countries ------------------------
p <- p + geom_path(data = gr_rob, aes(long, lat, group = group, fill = NULL),
              linetype = "solid", color = "grey80", alpha=.5)
# Grey for the non-data regions
p <- p + geom_polygon(data=the_whole, fill="grey50", colour = alpha("white", 1/2), size=.4, guide = FALSE)
p <- p + geom_polygon(aes(fill = subgroup), colour = NA)
p <- p + geom_polygon(fill=NA,colour = alpha("white", 1/2), size=.4, guide = FALSE)
# p <- p + scale_fill_manual(values=plot_colors(part = syb_part, length(unique(overview.df$subgroup)))[["Sub"]])
# p <- p + scale_fill_manual(values=c("#964B00", # Brown
#                                     "#A52A2A", # Red-Brown
#                                     "#9F8170", # Beaver
#                                     "#C3B091", # Khaki
#                                     "#F0DC82")) # Buff
# if (region_to_report == "COF")p <- p + scale_fill_manual(values = wes_palette("Cavalcanti"))
if (region_to_report == "COF")p <- p + scale_fill_manual(values = c("#8c510a","#d8b365","#f6e8c3","#c7eae5","#5ab4ac","#01665e"))
if (region_to_report != "COF")p <- p + scale_fill_manual(values=plot_colors(part = 1, length(unique(overview.df$subgroup)))[["Sub"]])
p <- p + theme(legend.position = c(0.05,0.05),
                          legend.justification=c(0,0),
                          legend.key.size=unit(6,'mm'),
                          legend.direction = "vertical",
                          legend.background=element_rect(colour=NA, fill=alpha("white", 1/3)),
                          #legend.background=element_rect(colour=NA, fill=NA),
                          legend.text=element_text(size=12),
                          legend.title=element_text(size=12),
                          title=element_text(size=16),
                          panel.background = element_blank(),
                          plot.background = element_blank(),
                          panel.grid.minor = element_blank(),
                          panel.grid.major = element_blank(),
                          axis.text = element_blank(),
                          axis.title = element_blank(),
                          axis.ticks = element_blank())
p <- p + guides(fill = guide_legend(title = map_unit, family="PT Sans",
                                     title.position = "top",
                                     title.hjust=0))
p <- p + guides(colour=FALSE)
p


```


<!-- %
% PPPPPPPPPPPPPPPPP                                               tttt            1111111
% P::::::::::::::::P                                           ttt:::t           1::::::1
% P::::::PPPPPP:::::P                                          t:::::t          1:::::::1
% PP:::::P     P:::::P                                         t:::::t          111:::::1
%   P::::P     P:::::Paaaaaaaaaaaaa  rrrrr   rrrrrrrrr   ttttttt:::::ttttttt       1::::1
%   P::::P     P:::::Pa::::::::::::a r::::rrr:::::::::r  t:::::::::::::::::t       1::::1
%   P::::PPPPPP:::::P aaaaaaaaa:::::ar:::::::::::::::::r t:::::::::::::::::t       1::::1
%   P:::::::::::::PP           a::::arr::::::rrrrr::::::rtttttt:::::::tttttt       1::::l
%   P::::PPPPPPPPP      aaaaaaa:::::a r:::::r     r:::::r      t:::::t             1::::l
%   P::::P            aa::::::::::::a r:::::r     rrrrrrr      t:::::t             1::::l
%   P::::P           a::::aaaa::::::a r:::::r                  t:::::t             1::::l
%   P::::P          a::::a    a:::::a r:::::r                  t:::::t    tttttt   1::::l
% PP::::::PP        a::::a    a:::::a r:::::r                  t::::::tttt:::::t111::::::111
% P::::::::P        a:::::aaaa::::::a r:::::r                  tt::::::::::::::t1::::::::::1
% P::::::::P         a::::::::::aa:::ar:::::r                    tt:::::::::::tt1::::::::::1
% PPPPPPPPPP          aaaaaaaaaa  aaaarrrrrrr                      ttttttttttt  111111111111 -->


```{r setup-code-part1}
knitr::read_chunk(paste0(master.root.dir,"input/code/code_part1.R"))
```

```{r part1_setup, eval=include_part1}
```


%    ___                                  _
%   / _ \  __   __   ___   _ __  __   __ (_)   ___  __      __
%  | | | | \ \ / /  / _ \ | '__| \ \ / / | |  / _ \ \ \ /\ / /
%  | |_| |  \ V /  |  __/ | |     \ V /  | | |  __/  \ V  V /
%   \___/    \_/    \___| |_|      \_/   |_|  \___|   \_/\_/
%


```{r P1overTEXT, eval=TRUE, short_text_ChartPage=P1over}
```


```{r P1overData,results='hide', cache=FALSE}
```


```{r P1overTOPRIGHT, eval=TRUE, top_right_plot=P1over, fig.height=top_right_plot_height, fig.width=top_right_plot_width}
```



```{r P1overLEFT, eval=TRUE, left_plot=P1over, fig.height=left_plot_height, fig.width=left_plot_width}
```

```{r P1overRIGHT, eval=TRUE ,right_plot=P1over, fig.height=right_plot_height, fig.width=right_plot_width}
```


```{r P1overBOTTOM, eval=TRUE, bottom_plot=P1over, fig.height=bottom_plot_height, fig.width=bottom_plot_width}
```


```{r P1overMAP, eval=TRUE, map_plot=P1over, fig.width=map.fig.width, fig.height= map.fig.height ,out.width=map.out.width, out.height=map.out.height, out.extra=map.out.extra}
```
